language: java

before_install:
    - sudo apt-get install -qq maven libprotoc-dev 
    #- wget -nc --no-check-certificate http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.bz2
    #- tar xvf protobuf-2.5.0.tar.bz2
    - wget -nc --no-check-certificate http://search.maven.org/remotecontent?filepath=com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar
    - wget -nc --no-check-certificate http://search.maven.org/remotecontent?filepath=junit/junit/4.11/junit-4.11.jar -O ./junit-4.11.jar
    - wget -nc --no-check-certificate http://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar -O hamcrest-core-1.3.jar
    - git clone https://github.com/zeromq/jeromq
    - wget -nc --no-check-certificate http://sourceforge.net/projects/lejos/files/lejos-NXJ/0.9.1beta/leJOS_NXJ_0.9.1beta-3.tar.gz/download -O ./leJOS_NXJ_0.9.1beta-3.tar.gz
    - tar -xvf leJOS_NXJ_0.9.1beta-3.tar.gz

install:
    #- cd protobuf-2.5.0 && ./configure
    #- sudo make install --quiet
    #- cd java && mvn install -P lite
    #- cd ../..
    - cd jeromq && sudo mvn install -q
    - cd ..

env:
    - JUNIT_DIR=. NXJ_HOME=leJOS_NXJ_0.9.1beta-3 HAMCREST_DIR=. JEROMQ_DIR=./jeromq PROTOBUF_DIR=.

script:
    - pwd
    - ant -version
    - ant junit-proxy -v 

notifications:
    recipients:
        - miludmann+travis@gmail.com
    email:
        on_success: change
        on_failure: always 
